; Listing generated by Microsoft (R) Optimizing Compiler Version 19.14.26429.4 

; Generated by VC++ for Common Language Runtime
.file "C:\Users\13131\AppData\Local\Temp\.NETFramework,Version=v4.0.AssemblyAttributes.cpp"
